### ISSUE TITLE
How to set this up?

### ISSUE THREAD

**Issue by CrashyBang** [fisherman/fish-vte#1]
I tried installing this but it does not seem to be working.

I can't find any reference to the plugin in: `/.config/fish/conf.d`

And it does not seem to be sourcing anything?

Cheers,
Otis.

**Comment by jbucaran** [comment]
@CrashyBang Hey. I think @MadcapJake is not watching the repo, which is why he didn't get a notification. Maybe he knows.

**Comment by CrashyBang** [comment]
Hey @jbucaran all good turns out I don't need now anyway but thank you for getting back.

**Comment by wehlutyk** [comment]
I'm re-asking this question as I'm running into the same problem: how does this need to be set up? Does the `fish_preexec` function not need to be registered with `--on-event fish_preexec`?
